language: ruby
env: DEBUG=true
rvm:
  - 2.2
  - 2.3
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
  - jruby-head
before_install: # https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script:
  - bundle exec rake
  - bundle exec yard --version && bundle exec yard || echo "Yard not available, is this an old ruby version?"
matrix:
  include:
    - rvm: 1.8.7
      dist: trusty
      gemfile: spec/gemfiles/Gemfile.18
    - rvm: jruby-18mode
      gemfile: spec/gemfiles/Gemfile.18
    - rvm: 1.9.3
      dist: trusty
      gemfile: spec/gemfiles/Gemfile.19
    - rvm: 2.0
      gemfile: spec/gemfiles/Gemfile.20
    - rvm: 2.1
      gemfile: spec/gemfiles/Gemfile.21
    - rvm: jruby-19mode
      gemfile: spec/gemfiles/Gemfile.19
